apiVersion : apps/v1
kind: Deployment
metadata:
  name: netcore5 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netcore5
  template:
    metadata:
      labels:
        app: netcore5 
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: netcore5 
          image: classicwebapp/netcore5
          ports:
          - containerPort: 80
